### ISSUE TITLE
Frontend unit test failure in 1.0.51

### ISSUE THREAD

**Issue by mfugate1** [CarnegieLearningWeb/UpGrade#133]
```
NewExperimentComponent
    ✗ should create
	TypeError: Cannot read property 'conditions' of undefined
	error properties: Object({ ngDebugContext: DebugContext_({ view: Object({ def: Object({ factory: Function, nodeFlags: 777771009, rootNodeFlags: 704643073, nodeMatchedQueries: 254, flags: 0, nodes: [ Object({ nodeIndex: 0, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, checkIndex: -1, flags: 671088640, childFlags: 0, directChildFlags: 0, childMatchedQueries: 0, ngContentIndex: -1, matchedQueries: Object({  }), matchedQueryIds: 0, references: Object({  }), childCount: 0, bindings: [  ], bindingFlags: 0, outputs: [  ], element: null, provider: null, text: null, query: Object({ id: 1, filterId: 2, bindings: [ Object ] }), ngContent: null }), Object({ nodeIndex: 1, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, checkIndex: 1, flags: 33554433, childFlags: 643553281, directChildFlags: 38983681, childMatchedQueries: 254, matchedQueries: Object({  }), matchedQueryIds: 0, references: Object({  }), ngContentIndex: null, childCount: 39, bindings: [ Object({ flags: 2, ns: '',  ...
	    at <Jasmine>
	    at ExperimentPostConditionComponent.ngOnChanges (http://localhost:9876/_karma_webpack_/webpack:/src/app/features/dashboard/home/components/experiment-post-condition/experiment-post-condition.component.ts:48:32)
	    at checkAndUpdateDirectiveInline (http://localhost:9876/_karma_webpack_/webpack:/home/runner/work/UpGrade/UpGrade/frontend/node_modules/@angular/core/fesm2015/core.js:24499:1)
	    at checkAndUpdateNodeInline (http://localhost:9876/_karma_webpack_/webpack:/home/runner/work/UpGrade/UpGrade/frontend/node_modules/@angular/core/fesm2015/core.js:35163:1)
	    at checkAndUpdateNode (http://localhost:9876/_karma_webpack_/webpack:/home/runner/work/UpGrade/UpGrade/frontend/node_modules/@angular/core/fesm2015/core.js:35102:1)
	    at debugCheckAndUpdateNode (http://localhost:9876/_karma_webpack_/webpack:/home/runner/work/UpGrade/UpGrade/frontend/node_modules/@angular/core/fesm2015/core.js:36124:36)
	    at debugCheckDirectivesFn (http://localhost:9876/_karma_webpack_/webpack:/home/runner/work/UpGrade/UpGrade/frontend/node_modules/@angular/core/fesm2015/core.js:36067:1)
	    at Object.eval [as updateDirectives] (ng:///DynamicTestModule/NewExperimentComponent.ngfactory.js:179:5)
	    at Object.debugUpdateDirectives [as updateDirectives] (http://localhost:9876/_karma_webpack_/webpack:/home/runner/work/UpGrade/UpGrade/frontend/node_modules/@angular/core/fesm2015/core.js:36055:1)
	    at checkAndUpdateView (http://localhost:9876/_karma_webpack_/webpack:/home/runner/work/UpGrade/UpGrade/frontend/node_modules/@angular/core/fesm2015/core.js:35067:1)
	    at callViewAction (http://localhost:9876/_karma_webpack_/webpack:/home/runner/work/UpGrade/UpGrade/frontend/node_modules/@angular/core/fesm2015/core.js:35433:1)
```

The changelog:
• 4df8eb87 code review changes for refactoring and minor edge case resolution (pratik)
• 0f900127 deleting condition assigned in post experiment rule will assign default condition (pratik)
• 803470ba edit post experiment conditions on saving midway with alert popup for saved experiment details (pratik)

**Comment by ppratikcr7** [comment]
@mfugate1 I have resolved this issue and created a PR. We suggest that for future PR merge it would be good if we can decouple the build and deploy into two different action files and trigger the deploy action file when the build is successful. For this we can change the branch settings as shown below with adding the build action yml:

<img width="1247" alt="Screenshot 2021-09-13 at 3 35 39 PM" src="https://user-images.githubusercontent.com/33730817/133068014-d20d50d3-fa27-44eb-b6db-d95dd5724b9b.png">

**Comment by mfugate1** [comment]
Yeah I've been slowly adding required status checks for PR merging in other CL repos, just not a high priority atm
