### ISSUE TITLE
FF Fix: Unknown error pops up in dev

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1724]
On nav to feature flags page, an error is popping up in dev. I wasn't able to reproduce in local, we should really have source-maps turned on for staging and qa builds so we can debug.

![Image](https://github.com/CarnegieLearningWeb/UpGrade/assets/97542869/356ff309-9178-4ffd-9c77-b4ef886ef56b)

**Comment by Yagnik56** [comment]
can you show the console what is the error?

**Comment by danoswaltCL** [comment]
I don't know if it will help, but you can see for yourself if you go to the dev environment and click on feature-flags.

main.a78a131e454bd69f.js:1 ERROR TypeError: Cannot read properties of undefined (reading 'onDestroy')
    at Object.Eb (main.a78a131e454bd69f.js:1:787668)
    at G (928.0329f751348e422a.js:1:1600)
    at hf (main.a78a131e454bd69f.js:1:716741)
    at zu (main.a78a131e454bd69f.js:1:724143)
    at dc (main.a78a131e454bd69f.js:1:724716)
    at Wx.createEmbeddedViewImpl (main.a78a131e454bd69f.js:1:729989)
    at hg.createEmbeddedView (main.a78a131e454bd69f.js:1:754572)
    at D._updateView (main.a78a131e454bd69f.js:1:623597)
    at set ngIfElse (main.a78a131e454bd69f.js:1:623221)
    at $m (main.a78a131e454bd69f.js:1:694742)

**Comment by danoswaltCL** [comment]
you're right, it disappeared! i wonder if your change to update the correct modules fixed something.... I also a see a mat-progress-spinner working across the root table now. It seems to be broken but at least it's showing up now, I had forgotten about that.
