### ISSUE TITLE
Fix backend Dockerfile 

### ISSUE THREAD

**Issue by mfugate1** [CarnegieLearningWeb/UpGrade#239]
It currently fails to build with this error:

```
=> ERROR [4/5] RUN cd packages/Upgrade && npm ci
------
 > [4/5] RUN cd packages/Upgrade && npm ci:
#7 0.745 npm ERR! @swc/core-android-arm64 not accessible from @swc/core
#7 0.751
#7 0.751 npm ERR! A complete log of this run can be found in:
#7 0.751 npm ERR!     /root/.npm/_logs/2022-02-01T13_48_26_081Z-debug.log
------
executor failed running [/bin/sh -c cd packages/Upgrade && npm ci]: exit code: 1
```

By updating npm to 7.9.0, I can get past that error but then run into this:

```
/workspace/UpGrade/backend/packages/Upgrade/node_modules/@node-rs/helper/lib/loader.js:50
    throw new Error(errorMsg);
    ^

Error: Can not load bindings

    at loadBinding (/workspace/UpGrade/backend/packages/Upgrade/node_modules/@node-rs/helper/lib/loader.js:50:11)
    at Object.<anonymous> (/workspace/UpGrade/backend/packages/Upgrade/node_modules/@swc/core/index.js:37:43)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at create (/workspace/UpGrade/backend/packages/Upgrade/node_modules/ts-node/dist/transpilers/swc.js:24:23)
    at create (/workspace/UpGrade/backend/packages/Upgrade/node_modules/ts-node/dist/index.js:262:28)
```

Getting this to work will allow me to start setting up this infrastructure in ECS, as well as enabling tests for the CI script.

**Comment by mfugate1** [comment]
Caused by [65767af7fe057a1c7eaf44b08de4db5f00ee8d6c](https://github.com/CarnegieLearningWeb/UpGrade/commit/65767af7fe057a1c7eaf44b08de4db5f00ee8d6c)

It would be nice to take this opportunity to update the backend to use nodejs 16.
