### ISSUE TITLE
Null metrics log data is causing errors in production

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#711]
**Describe the bug**
In `api/log` this error has been showing up for a long time, let's solve it.

```
TypeError: Cannot read property 'id' of null
    at /usr/src/app/packages/Upgrade/src/api/services/ExperimentAssignmentService.ts:1014:28
    at Array.forEach (<anonymous>)
    at ExperimentAssignmentService.<anonymous> (/usr/src/app/packages/Upgrade/src/api/services/ExperimentAssignmentService.ts:1005:14)
    at Generator.next (<anonymous>)
                           at fulfilled (/usr/src/app/packages/Upgrade/node_modules/tslib/tslib.js:114:62)
    at runMicrotasks (<anonymous>)
```

When I dig into the code, it appears that `toCheckMetrics` can come as `nul`l, which is not handled in the code. (Importantly it's not `undefined`, so this `null` value must coming from the data returned in `this.logRepository.getMetricUniquifierData`)

Should this be handled as potentially null? Or is a null value here a sign that something else is wrong?

ExperimentAssignmentService.ts

```typescript
const logGroup = await this.logRepository.getMetricUniquifierData(metricKeys, uniquifierKeys, userId);

    const mergedLogGroup = [];

    // merge the metrics field
    logGroup.forEach((logData, index) => {
      if (logData !== null) {
        // tslint:disable-next-line:no-shadowed-variable
        const { id, uniquifier, data, timestamp, key } = logData;
        const metric_keys = [key];
        for (let i = index + 1; i < logGroup.length; i++) {
          const toCheckMetrics = logGroup[i];
          // merge the data log here
          if (
            toCheckMetrics.id === id && //<---------- toCheckMetrics is coming as null
            toCheckMetrics.uniquifier === uniquifier &&
            isequal(toCheckMetrics.data, data) &&
            new Date(toCheckMetrics.timestamp).getTime() === new Date(timestamp).getTime()
          ) {
            metric_keys.push(toCheckMetrics.key);
            logGroup[i] = null;
          }
        }
        mergedLogGroup.push({ ...logData, key: metric_keys });
      }
    });
```

**To Reproduce**

The above code (which is still in the repo) loops through an array - and inside that loop loops through the remaining elements of that *same* array, possibly setting one or more of them to null! That means that we're setting an element to null that we haven't gotten to yet. So of course this error occurs. -- Ben (I couldn't add a comment, but I *could* add to Dan's comment, apparently as him)

**Comment by jreddig** [comment]
Upon further investigation, it's because of the line `logGroup[i] = null;`. In this real example, logGroup comes in as a complete array
```
[

  {

    data: { totalTimeSeconds: 215473, totalProblemsCompleted: 310 },

    uniquifier: '1',

    timestamp: 2022-12-09T01:54:12.135Z,

    id: 215098,

    key: 'totalTimeSeconds'

  },

  {

    data: { masteryWorkspace: [Object] },

    uniquifier: '2022-09-14T03:46:34.030Z',

    timestamp: 2022-12-09T01:54:12.135Z,

    id: 502390,

    key: 'masteryWorkspace@__@analyzing_models_2step_rationals@__@errorCount'

  },

  {

    data: { masteryWorkspace: [Object] },

    uniquifier: '2022-11-25T02:43:42.765Z',

    timestamp: 2022-12-09T01:54:12.135Z,

    id: 502529,

    key: 'masteryWorkspace@__@analyzing_models_2step_rationals@__@errorCount'

  },

  {

    data: { masteryWorkspace: [Object] },

    uniquifier: '2022-11-25T02:43:42.765Z',

    timestamp: 2022-12-09T01:54:12.135Z,

    id: 502529,

    key: 'masteryWorkspace@__@analyzing_models_2step_rationals@__@problemsCompleted'

  },

  {

    data: { masteryWorkspace: [Object] },

    uniquifier: '2022-11-25T02:43:42.765Z',

    timestamp: 2022-12-09T01:54:12.135Z,

    id: 502529,

    key: 'masteryWorkspace@__@analyzing_models_2step_rationals@__@timeSeconds'

  },

  {

    data: { masteryWorkspace: [Object] },

    uniquifier: '2022-09-14T03:46:34.030Z',

    timestamp: 2022-12-09T01:54:12.135Z,

    id: 502390,

    key: 'masteryWorkspace@__@analyzing_models_2step_rationals@__@problemsCompleted'

  },

  {

    data: { masteryWorkspace: [Object] },

    uniquifier: '2022-09-14T03:46:34.030Z',

    timestamp: 2022-12-09T01:54:12.135Z,

    id: 502390,

    key: 'masteryWorkspace@__@analyzing_models_2step_rationals@__@timeSeconds'

  }

]
```
But when iterating through, the order is changed:
```
0 1 {

  data: { masteryWorkspace: { analyzing_models_2step_rationals: [Object] } },

  uniquifier: '2022-09-14T03:46:34.030Z',

  timestamp: 2022-12-09T01:54:12.135Z,

  id: 502390,

  key: 'masteryWorkspace@__@analyzing_models_2step_rationals@__@errorCount'

}

0 2 {

  data: { masteryWorkspace: { analyzing_models_2step_rationals: [Object] } },

  uniquifier: '2022-11-25T02:43:42.765Z',

  timestamp: 2022-12-09T01:54:12.135Z,

  id: 502529,

  key: 'masteryWorkspace@__@analyzing_models_2step_rationals@__@errorCount'

}

0 3 {

  data: { masteryWorkspace: { analyzing_models_2step_rationals: [Object] } },

  uniquifier: '2022-11-25T02:43:42.765Z',

  timestamp: 2022-12-09T01:54:12.135Z,

  id: 502529,

  key: 'masteryWorkspace@__@analyzing_models_2step_rationals@__@problemsCompleted'

}

0 4 {

  data: { masteryWorkspace: { analyzing_models_2step_rationals: [Object] } },

  uniquifier: '2022-11-25T02:43:42.765Z',

  timestamp: 2022-12-09T01:54:12.135Z,

  id: 502529,

  key: 'masteryWorkspace@__@analyzing_models_2step_rationals@__@timeSeconds'

}

0 5 {

  data: { masteryWorkspace: { analyzing_models_2step_rationals: [Object] } },

  uniquifier: '2022-09-14T03:46:34.030Z',

  timestamp: 2022-12-09T01:54:12.135Z,

  id: 502390,

  key: 'masteryWorkspace@__@analyzing_models_2step_rationals@__@problemsCompleted'

}

0 6 {

  data: { masteryWorkspace: { analyzing_models_2step_rationals: [Object] } },

  uniquifier: '2022-09-14T03:46:34.030Z',

  timestamp: 2022-12-09T01:54:12.135Z,

  id: 502390,

  key: 'masteryWorkspace@__@analyzing_models_2step_rationals@__@timeSeconds'

}

0 7 {

  data: { totalTimeSeconds: 215473, totalProblemsCompleted: 310 },

  uniquifier: '1',

  timestamp: 2022-12-09T01:54:12.135Z,

  id: 215098,

  key: 'totalProblemsCompleted'

}

```
And the wrong element is set to null, further down in the array so `toCheckMetrics` is null
```
[

  {

    data: { totalTimeSeconds: 215473, totalProblemsCompleted: 310 },

    uniquifier: '1',

    timestamp: 2022-12-09T01:54:12.135Z,

    id: 215098,

    key: 'totalTimeSeconds'

  },

  {

    data: { masteryWorkspace: [Object] },

    uniquifier: '2022-09-14T03:46:34.030Z',

    timestamp: 2022-12-09T01:54:12.135Z,

    id: 502390,

    key: 'masteryWorkspace@__@analyzing_models_2step_rationals@__@errorCount'

  },

  {

    data: { masteryWorkspace: [Object] },

    uniquifier: '2022-11-25T02:43:42.765Z',

    timestamp: 2022-12-09T01:54:12.135Z,

    id: 502529,

    key: 'masteryWorkspace@__@analyzing_models_2step_rationals@__@errorCount'

  },

  {

    data: { masteryWorkspace: [Object] },

    uniquifier: '2022-11-25T02:43:42.765Z',

    timestamp: 2022-12-09T01:54:12.135Z,

    id: 502529,

    key: 'masteryWorkspace@__@analyzing_models_2step_rationals@__@problemsCompleted'

  },

  {

    data: { masteryWorkspace: [Object] },

    uniquifier: '2022-11-25T02:43:42.765Z',

    timestamp: 2022-12-09T01:54:12.135Z,

    id: 502529,

    key: 'masteryWorkspace@__@analyzing_models_2step_rationals@__@timeSeconds'

  },

  {

    data: { masteryWorkspace: [Object] },

    uniquifier: '2022-09-14T03:46:34.030Z',

    timestamp: 2022-12-09T01:54:12.135Z,

    id: 502390,

    key: 'masteryWorkspace@__@analyzing_models_2step_rationals@__@problemsCompleted'

  },

  {

    data: { masteryWorkspace: [Object] },

    uniquifier: '2022-09-14T03:46:34.030Z',

    timestamp: 2022-12-09T01:54:12.135Z,

    id: 502390,

    key: 'masteryWorkspace@__@analyzing_models_2step_rationals@__@timeSeconds'

  },

  null
]
```


However, when I build UpGrade 4.0 in my local, load it with the current prod data, and send this same requests that fails in prod, the log processes with no errors.

**Comment by jreddig** [comment]
This error stopped appearing once we deployed UpGrade 4x to production

<img width="1553" alt="Screenshot 2023-07-03 at 9 35 02 AM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/97543136/6d262b6a-9230-4a12-a852-8477450ecdd2">

**Comment by jreddig** [comment]
Spoke too soon. Log data started coming in and the error is back. 
`ExperimentAssignmentService.ts:1054:28` of release 4 branch

**Comment by danoswaltCL** [comment]
if someone is available to tackle this, it would help us really help us tamp down possible errors in production. Jenn had some deep analysis that I'm not sure I completely understand; if someone can take a look and if it's a pretty safe / easy fix, maybe we can get this into production as a hotfix also while we're cleaning things up.

**Comment by ppratikcr7** [comment]
@danoswaltCL We would need the prod data dump (DB) for this to recreate.

**Comment by danoswaltCL** [comment]
QA: Dan

**Comment by danoswaltCL** [comment]
@bcb37 do you have a good example request that can be used to test this? Particularly if you have one that will succeed in `dev` now but fail with the expected error if I request against `release/v5` branch in local or staging?

**Comment by bcb37** [comment]
> @bcb37 do you have a good example request that can be used to test this? Particularly if you have one that will succeed in `dev` now but fail with the expected error if I request against `release/v5` branch in local or staging?

Not for this, no. That's why I think it might me architecture/race condition-related. The closest I've gotten is to make a request with a number in the 'id' field, which reliably throws the error (because of postgres converting under-the-hood at the wrong time). Updating typeorm to version 0.2.40 and using `upsert()` fixes that, but things are being done with the return value from `save()` that I have not been able to puzzle out.

**Comment by bcb37** [comment]
> @bcb37 do you have a good example request that can be used to test this? Particularly if you have one that will succeed in `dev` now but fail with the expected error if I request against `release/v5` branch in local or staging?

Yes, that was the purpose of the unit test in this pr. The request body in the unit test fails with the old version of the algorithm.

**Comment by danoswaltCL** [comment]
This is for the "null" metrics log problem, not the .save thing. Wanted to QA the fix you put in to get it over to Done.

**Comment by danoswaltCL** [comment]
> Yes, that was the purpose of the unit test in this pr. The request body in the unit test fails with the old version of the algorithm.

Oh right right, you said that, ty i can use that.

**Comment by danoswaltCL** [comment]
QA: ✅
