### ISSUE TITLE
Lambda Github-Action issue

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#738]
**Describe the bug**
```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/runner/work/UpGrade/UpGrade/backend/packages/Scheduler/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/runner/work/UpGrade/UpGrade/backend/packages/Scheduler/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/runner/work/UpGrade/UpGrade/backend/packages/Scheduler/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/runner/work/UpGrade/UpGrade/backend/packages/Scheduler/node_modules/webpack/lib/NormalModule.js:[50](https://github.com/CarnegieLearningWeb/UpGrade/actions/runs/4385917663/jobs/7679399547#step:3:51)3:5
    at /home/runner/work/UpGrade/UpGrade/backend/packages/Scheduler/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/runner/work/UpGrade/UpGrade/backend/packages/Scheduler/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/runner/work/UpGrade/UpGrade/backend/packages/Scheduler/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/runner/work/UpGrade/UpGrade/backend/packages/Scheduler/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/runner/work/UpGrade/UpGrade/backend/packages/Scheduler/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/home/runner/work/UpGrade/UpGrade/backend/packages/Scheduler/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at makeSourceMapAndFinish (/home/runner/work/UpGrade/UpGrade/backend/packages/Scheduler/node_modules/ts-loader/dist/index.js:88:5)
    at successLoader (/home/runner/work/UpGrade/UpGrade/backend/packages/Scheduler/node_modules/ts-loader/dist/index.js:68:9)
    at Object.loader (/home/runner/work/UpGrade/UpGrade/backend/packages/Scheduler/node_modules/ts-loader/dist/index.js:22:12)
    at LOADER_EXECUTION (/home/runner/work/UpGrade/UpGrade/backend/packages/Scheduler/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/home/runner/work/UpGrade/UpGrade/backend/packages/Scheduler/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/home/runner/work/UpGrade/UpGrade/backend/packages/Scheduler/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/runner/work/UpGrade/UpGrade/backend/packages/Scheduler/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/runner/work/UpGrade/UpGrade/backend/packages/Scheduler/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:[55](https://github.com/CarnegieLearningWeb/UpGrade/actions/runs/4385917663/jobs/7679399547#step:3:56):16)
    at /home/runner/work/UpGrade/UpGrade/backend/packages/Scheduler/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/runner/work/UpGrade/UpGrade/backend/packages/Scheduler/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:[68](https://github.com/CarnegieLearningWeb/UpGrade/actions/runs/4385917663/jobs/7679399547#step:3:69):3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.14.2
```

**To Reproduce**
Run "Create Release" Github Action

**Additional context**
Mostly creating this for awareness later; currently we run our github actions from node 16 and this particular job used 18 for some reason, so I'll try running it on 16 and see if this error "goes away", but eventually it will need addressed.

**Comment by amurphy-cl** [comment]
Closing as it's duplicated in #982
