### ISSUE TITLE
QueryFailedError: column factors.decisionPointId does not exist

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#762]
**Describe the bug**
I've been on the `enhancement/new-factorial-designs` branch to test the factorial experiments which UpGrade worked fine, but when I switched back to the `dev` branch, I'm getting the following error in the backend Terminal console:

```
QueryFailedError: column factors.decisionPointId does not exist
    at QueryFailedError.TypeORMError [as constructor] (/Users/zlee/Desktop/code/UpGrade/backend/packages/Upgrade/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/Users/zlee/Desktop/code/UpGrade/backend/packages/Upgrade/src/error/QueryFailedError.ts:9:9)
    at PostgresQueryRunner.<anonymous> (/Users/zlee/Desktop/code/UpGrade/backend/packages/Upgrade/src/driver/postgres/PostgresQueryRunner.ts:258:19)
    at step (/Users/zlee/Desktop/code/UpGrade/backend/packages/Upgrade/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/Users/zlee/Desktop/code/UpGrade/backend/packages/Upgrade/node_modules/tslib/tslib.js:124:57)
    at rejected (/Users/zlee/Desktop/code/UpGrade/backend/packages/Upgrade/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I even tried clearing the DB with `api/clearDB` but the error still occurred.

**To Reproduce**
1. Checkout to the `dev` branch
2. Signout and Login to UpGrade
3. The page doesn't load and the console shows `http://localhost:3030/api/experiments/paginated net::ERR_EMPTY_RESPONSE` error
4. In the backend Terminal console, the error "QueryFailedError: column factors.decisionPointId does not exist" is shown

**Expected behavior**
The error should not happen in the dev branch

**Comment by jreddig** [comment]
I don't get this error after re-building dev branch. Can you try `make destroy`, `make setup-local`, then `make`?

**Comment by zackcl** [comment]
@jreddig Thank you for your clarification. I'm not using docker so I just tried clearing the Postgres data and reinitializing the server, and it works fine now. Thank you!
