### ISSUE TITLE
Condition auto-resorting / Database error for backend 1.0.53

### ISSUE THREAD

**Issue by mfugate1** [CarnegieLearningWeb/UpGrade#90]
08931634 new column 'order' for condition and partition for sustaining orginal order (Ridham)

```query failed: ALTER TABLE "experiment_condition" ADD "order" integer NOT NULL
error: error: column "order" contains null values
    at Connection.parseE (/usr/src/app/packages/Upgrade/node_modules/pg/lib/connection.js:614:13)
    at Connection.parseMessage (/usr/src/app/packages/Upgrade/node_modules/pg/lib/connection.js:413:19)
    at Socket.<anonymous> (/usr/src/app/packages/Upgrade/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:203:13)
    at Socket.EventEmitter.emit (domain.js:471:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17) {
  name: 'error',
  length: 135,
  severity: 'ERROR',
  code: '23502',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'experiment_condition',
  column: 'order',
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '4891',
  routine: 'ATRewriteTable'```

**Comment by RidhamShah** [comment]
created PR  - [PR](https://github.com/CarnegieLearningWeb/UpGrade/pull/92)

**Comment by mfugate1** [comment]
Still seeing this issue with that PR merged in version 1.0.55:
```
query: ALTER TABLE "experiment_condition" ADD "order" integer NOT NULL
query failed: ALTER TABLE "experiment_condition" ADD "order" integer NOT NULL
error: error: column "order" contains null values
    at Connection.parseE (/usr/src/app/packages/Upgrade/node_modules/pg/lib/connection.js:614:13)
    at Connection.parseMessage (/usr/src/app/packages/Upgrade/node_modules/pg/lib/connection.js:413:19)
    at Socket.<anonymous> (/usr/src/app/packages/Upgrade/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:203:13)
    at Socket.EventEmitter.emit (domain.js:471:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17) {
  name: 'error',
  length: 135,
  severity: 'ERROR',
  code: '23502',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'experiment_condition',
  column: 'order',
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '4891',
  routine: 'ATRewriteTable'
```

**Comment by nirmalpatel** [comment]
Thanks @mfugate1 for the info. We will work on our CI pipeline first, recreate the issue, and then verify the solution for the next PR.

**Comment by nirmalpatel** [comment]
@mfugate1 can you tell what is the commit ID of the current live deployment? (or the backend and frontend version)

**Comment by mfugate1** [comment]
For our staging environment:
Backend: 1.0.52 (7642243)
Frontend: 1.0.42 (e29c4b8)
